package org.onlinetaskforce.common.exceptions;

/**
 * @author jordens
 * @since 28/03/13
 */
public interface BusinessExceptionKeys {
    String BE_KEY_TOO_MANY_FILES = "BE_KEY_TOO_MANY_FILES";
    String BE_KEY_MAIL_SEND_FAILURE = "BE_KEY_MAIL_SEND_FAILURE";
    String BE_KEY_SAVE_WAGEN_FAILURE = "BE_KEY_SAVE_WAGEN_FAILURE";
    String BE_KEY_SAVE_WAGEN_INVOLVES_CANCELLATIONS = "BE_KEY_SAVE_WAGEN_INVOLVES_CANCELLATIONS";
    String BE_KEY_SAVE_RESERVATIE_FAILURE = "BE_KEY_SAVE_RESERVATIE_FAILURE";
    String BE_KEY_SAVE_USER_FAILURE = "BE_KEY_SAVE_USER_FAILURE";
    String BE_KEY_WW_OLD_INVALID = "BE_KEY_WW_OLD_INVALID";
    String BE_KEY_WW_OLD_EQUALS_NEW = "BE_KEY_WW_OLD_EQUALS_NEW";
}
